services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.0
    container_name: elasticsearch
    deploy:
      resources:
        limits:
          memory: 8g
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data
      - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      retries: 5
    networks:
      - riws

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-front
    container_name: frontend-container
    ports:
      - "3000:3000"
    restart: always
    networks:
      - riws

  initializer:
    build:
      context: .
      dockerfile: Dockerfile-initializer
    container_name: index-initializer
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./index-initializer:/app/initialization
    networks:
      - riws

volumes:
  elastic:

networks:
  riws:
    driver: bridge